modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.annoyingvillagers]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="epicfight"
    mandatory=true
    versionRange="[20.9.7]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="wom"
    mandatory=true
    versionRange="[20.1, )"
    ordering="AFTER"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="falchionmoveset"
    mandatory=true
    versionRange="[20.8, )"
    ordering="AFTER"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="indestructible"
    mandatory=true
    versionRange="[20.9, )"
    ordering="AFTER"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="dualaxes"
    mandatory=true
    versionRange="[20.9.9.2]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="cdmoveset"
    mandatory=true
    versionRange="[1.28]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="player_mobs"
    mandatory=true
    versionRange="[4.1, )"
    ordering="AFTER"
    side="BOTH"
[[dependencies.annoyingvillagers]]
    modId="aaa_particles"
    mandatory=true
    versionRange="[1.4.11, )"
    ordering="NONE"
    side="CLIENT"