modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="annoyingvillagers"
version="${file.jarVersion}"
displayName="Annoying Villagers"
credits="Thanks for Chinese dev team"
authors="pla_is_me"
description='''
Pla ported this mod from annoying villlagers modpack Chinese version.
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"