package com.pla.annoyingvillagers.init;


import com.pla.annoyingvillagers.AnnoyingVillagers;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class AnnoyingVillagersModCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, AnnoyingVillagers.MODID);

    public static final RegistryObject<CreativeModeTab> AV_TAB = CREATIVE_MODE_TABS.register("annoyingvillagers_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(AnnoyingVillagersModItems.LEGENDARY_SWORD.get()))
                    .title(Component.translatable("creativetab.annoyingvillagers_tab"))
                    .displayItems((pParameters, pOutput) -> {
                        pOutput.accept(AnnoyingVillagersModItems.HEROBRINE_CLONE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.SHADOW_HEROBRINE_CLONE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.HEROBRINE_CHRIS_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.HEROBRINE_GREG_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.LOW_HEROBRINE_CLONE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.LOW_SHADOW_HEROBRINE_CLONE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.HEROBRINE_7_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.NULL_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.ARMORED_HEROBRINE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.DARK_HEROBRINE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.GLAIVE_HEROBRINE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.REAPER_HEROBRINE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.SWORDSMAN_HEROBRINE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.SLEDGEHAMMER_HEROBRINE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.AEGIS_HEROBRINE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLUE_DEMON_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.VILLAGER_SCOUT_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.VILLAGER_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLUE_VILLAGER_GENERAL_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.GREEN_VILLAGER_GENERAL_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.RED_VILLAGER_GENERAL_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.PURPLE_VILLAGER_GENERAL_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.STEVE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.ANGRY_STEVE_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.ALEX_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.CHRIS_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.JEV_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.PLAYER_NPC_SPAWN_EGG.get());
                        pOutput.accept(AnnoyingVillagersModItems.ENCHANT_BED_ITEM.get());
                        pOutput.accept(AnnoyingVillagersModItems.ENCHANTED_ARROW.get());
                        pOutput.accept(AnnoyingVillagersModItems.VILLAGER_HEAD.get());
                        pOutput.accept(AnnoyingVillagersModItems.JEV_GLASSES.get());
                        pOutput.accept(AnnoyingVillagersModItems.JEV_BOOK.get());
                        pOutput.accept(AnnoyingVillagersModItems.JEV_PENCIL.get());
                        pOutput.accept(AnnoyingVillagersModItems.DEMONIAC_VOLTAGE_REAVER_HILT.get());
                        pOutput.accept(AnnoyingVillagersModItems.DEMONIAC_VOLTAGE_REAVER_FRAGMENT.get());
                        pOutput.accept(AnnoyingVillagersModItems.DEMONIAC_VOLTAGE_REAVER_BLADE.get());
                        pOutput.accept(AnnoyingVillagersModItems.POISON_EGG_ITEM.get());
                        pOutput.accept(AnnoyingVillagersModItems.ENCHANTED_ENDER_PEARL.get());
                        pOutput.accept(AnnoyingVillagersModItems.CRAFTING_TABLE.get());
                        pOutput.accept(AnnoyingVillagersModItems.WOODEN_DOOR.get());
                        pOutput.accept(AnnoyingVillagersModItems.TRAPDOOR.get());
                        pOutput.accept(AnnoyingVillagersModItems.LADDER.get());
                        pOutput.accept(AnnoyingVillagersModItems.HEROBRINE_ENDER_EYE.get());
                        pOutput.accept(AnnoyingVillagersModItems.SHADOW_OBSIDIAN_PILLAR.get());
                        pOutput.accept(AnnoyingVillagersModItems.SHADOW_OBSIDIAN_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.SHADOW_OBSIDIAN_WEAPON.get());
                        pOutput.accept(AnnoyingVillagersModItems.OBSIDIAN_WEAPON.get());
                        pOutput.accept(AnnoyingVillagersModItems.BEDROCK_WEAPON.get());
                        pOutput.accept(AnnoyingVillagersModItems.ENDER_GLAIVE.get());
                        pOutput.accept(AnnoyingVillagersModItems.ENDER_SLAYER_SCYTHE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DEMONIAC_VOLTAGE_REAVER.get());
                        pOutput.accept(AnnoyingVillagersModItems.OBSIDIAN_SLEDGEHAMMER.get());
                        pOutput.accept(AnnoyingVillagersModItems.ENDER_AEGIS.get());
                        pOutput.accept(AnnoyingVillagersModItems.NULL_WEAPON.get());
                        pOutput.accept(AnnoyingVillagersModItems.LEGENDARY_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLUE_DEMON_TRIDENT.get());
                        pOutput.accept(AnnoyingVillagersModItems.WARDEN_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DARKNESS_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.RED_STEEL_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.HOLY_LLAMA_HAMMER.get());
                        pOutput.accept(AnnoyingVillagersModItems.NULL_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.NULL_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.NULL_PICKAXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.NULL_SHOVEL.get());
                        pOutput.accept(AnnoyingVillagersModItems.NULL_HOE.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLACK_FIRE_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLUE_FLAME_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.CENTRANOS_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.CLOW_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_ATTRACTOR_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_BLASTER_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.HACKER_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_WARBLADE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_FALCHION.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_GREAT_FALCHION.get());
                        pOutput.accept(AnnoyingVillagersModItems.NETHERITE_FALCHION.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_SABRE.get());
                        pOutput.accept(AnnoyingVillagersModItems.NETHERITE_SABRE.get());
                        pOutput.accept(AnnoyingVillagersModItems.HOOKED_DIAMOND_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.HOOKED_GOLDEN_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.HOOKED_IRON_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.IRON_CLEAVER.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_LAEVATEINN.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_LONGSWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.GOLDEN_LONGSWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.IRON_LONGSWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_CHIPPED_LONGSWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_GREATSWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DNAX_HOOKED_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.FLANKER_HOOKED_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.GREAT_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.IRON_TWIN_BLADE_KATANA.get());
                        pOutput.accept(AnnoyingVillagersModItems.PALADIN_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_GREATSWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_LONGSWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_KNIGHT_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.JADE_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.RED_DIAMOND_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.THUNDER_DIAMOND_BLADE.get());
                        pOutput.accept(AnnoyingVillagersModItems.WOOPIE_THE_SWORD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_HALBERD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_GREATAXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_BATTLEAXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.EARTH_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.EXTERMINATOR_BATTLEAXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.GIANT_NETHERITE_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.RED_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.IRON_DOUBLE_BLADED_HALBERD.get());
                        pOutput.accept(AnnoyingVillagersModItems.IRON_GREATAXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.IRON_HALBERD.get());
                        pOutput.accept(AnnoyingVillagersModItems.NETHERITE_GREATAXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.SAMANTHA_THE_KILLER_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.SPEAR_AXE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_ARMBLADE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_DAGGER.get());
                        pOutput.accept(AnnoyingVillagersModItems.KNIFE.get());
                        pOutput.accept(AnnoyingVillagersModItems.GOLDEN_MOON_BLADE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_MOON_BLADE.get());
                        pOutput.accept(AnnoyingVillagersModItems.NETHERITE_KNIFE.get());
                        pOutput.accept(AnnoyingVillagersModItems.GEM_SHIELD.get());
                        pOutput.accept(AnnoyingVillagersModItems.HEATER_SHIELD.get());
                        pOutput.accept(AnnoyingVillagersModItems.JESSICA_THE_DARK_SHIELD.get());
                        pOutput.accept(AnnoyingVillagersModItems.NETHERITE_SHIELD.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_BOLT.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLACKSCRATCHER.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_SICKLE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_SPEAR.get());
                        pOutput.accept(AnnoyingVillagersModItems.DOUBLE_DIAMOND_GLAIVE.get());
                        pOutput.accept(AnnoyingVillagersModItems.IRON_SICKLE.get());
                        pOutput.accept(AnnoyingVillagersModItems.NETHERITE_SPEAR.get());
                        pOutput.accept(AnnoyingVillagersModItems.TWIN_DIAMOND_SPEAR.get());
                        pOutput.accept(AnnoyingVillagersModItems.GOLDEN_MACE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_MACE.get());
                        pOutput.accept(AnnoyingVillagersModItems.DIAMOND_SHEAR.get());
                        pOutput.accept(AnnoyingVillagersModItems.COMPRESSED_DIAMOND.get());
                        pOutput.accept(AnnoyingVillagersModItems.DARK_NETHERITE.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY.get());
                        pOutput.accept(AnnoyingVillagersModItems.PURPLE_GEM.get());
                        pOutput.accept(AnnoyingVillagersModItems.HEROBRINE_OBSIDIAN_DIAMOND_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.HEROBRINE_OBSIDIAN_DIAMOND_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLUE_DEMON_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.BROKEN_DIAMOND_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.BROKEN_DIAMOND_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.BROKEN_DIAMOND_LEGGINGS.get());
                        pOutput.accept(AnnoyingVillagersModItems.BROKEN_DIAMOND_BOOTS.get());
                        pOutput.accept(AnnoyingVillagersModItems.COMPRESSED_DIAMOND_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.COMPRESSED_DIAMOND_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.COMPRESSED_DIAMOND_LEGGINGS.get());
                        pOutput.accept(AnnoyingVillagersModItems.COMPRESSED_DIAMOND_BOOTS.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_LEGGINGS.get());
                        pOutput.accept(AnnoyingVillagersModItems.RUBY_BOOTS.get());
                        pOutput.accept(AnnoyingVillagersModItems.EMERALD_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.EMERALD_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.EMERALD_LEGGINGS.get());
                        pOutput.accept(AnnoyingVillagersModItems.EMERALD_BOOTS.get());
                        pOutput.accept(AnnoyingVillagersModItems.UNLIGHT_DIAMOND_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.UNLIGHT_DIAMOND_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.UNLIGHT_DIAMOND_LEGGINGS.get());
                        pOutput.accept(AnnoyingVillagersModItems.UNLIGHT_DIAMOND_BOOTS.get());
                        pOutput.accept(AnnoyingVillagersModItems.VILLAGER_SCOUT_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.RED_VILLAGER_GENERAL_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.RED_VILLAGER_GENERAL_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLUE_VILLAGER_GENERAL_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.BLUE_VILLAGER_GENERAL_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.GREEN_VILLAGER_GENERAL_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.GREEN_VILLAGER_GENERAL_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.PURPLE_VILLAGER_GENERAL_HELMET.get());
                        pOutput.accept(AnnoyingVillagersModItems.PURPLE_VILLAGER_GENERAL_CHESTPLATE.get());
                        pOutput.accept(AnnoyingVillagersModItems.VILLAGER_GENERAL_LEGGINGS.get());
                        pOutput.accept(AnnoyingVillagersModItems.VILLAGER_GENERAL_BOOTS.get());
                    })
                    .build());


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}