package com.pla.annoyingvillagers.combatbehaviour;

import com.pla.annoyingvillagers.gameasset.AVAnimations;
import net.shelmarow.combat_evolution.ai.CECombatBehaviors;
import reascer.wom.gameasset.animations.weapons.AnimsHerrscher;
import yesman.epicfight.gameasset.Animations;
import yesman.epicfight.world.capabilities.entitypatch.MobPatch;

public class NullSkeletonSword {
    public static final CECombatBehaviors.Builder<MobPatch<?>> AV_SWORD = CECombatBehaviors.builder()
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(2.0D)
                            .weight(1000.0D)
                            .maxCooldown (0)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canExecute)
                                            .withinDistance(0.0D, 5.0D)
                                            .animationBehavior(Animations.BIPED_SNEAK, 0.0F)
                                            .addExBehavior(CombatCommon::performExecute)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(40.0D)
                            .maxCooldown(20)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 3.0D)
                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 3.0D)
                                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_1, 0.0F).addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 3.0D)
                                                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_2, 0.0F)
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_DASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_1, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(Animations.SWEEPING_EDGE, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_C, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_DASH, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_RUSH, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_STEP_LEFT, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AIR_SLASH, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_2, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_RIGHT, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWEEPING_EDGE, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_1, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_3, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_AIR_SLASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_H, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.KICK_4, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(Animations.SWEEPING_EDGE, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_RIGHT, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_DASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_C, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_1, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_STEP_LEFT, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_AIR_SLASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(AVAnimations.KICK_1, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_STEP_FORWARD, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_DASH, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_2, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_RIGHT, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWEEPING_EDGE, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_RUSH, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_STEP_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_DASH, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(AVAnimations.KICK_3, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_STEP_LEFT, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AIR_SLASH, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.KICK_H, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_1, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_STEP_RIGHT, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(Animations.SWEEPING_EDGE, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(Animations.SWORD_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(AVAnimations.KICK_4, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_STEP_FORWARD, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AUTO3, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_1, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(Animations.SWORD_DASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AnimsHerrscher.HERRSCHER_AUTO_2, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(AVAnimations.KICK_C, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_STEP_BACKWARD, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(20.0D)
                            .maxCooldown (80)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .withinDistance(0.0D, 3.0D)
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .withinDistance(0.0D, 3.0D)
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                            )
                                            )
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(10.0D)
                            .maxCooldown (80)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_DASH, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWORD_AIR_SLASH, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.SWEEPING_EDGE, 0.0F)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(2.0D)
                            .maxCooldown(80)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.KICK_1, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.KICK_2, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.KICK_3, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.KICK_4, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.KICK_C, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.KICK_RUSH, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.KICK_H, 0.0F)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(30.0D)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .custom(CombatCommon::canPerformGuarding)
                                            .guard(40)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(10.0D)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.BIPED_STEP_BACKWARD, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.BIPED_STEP_FORWARD, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.BIPED_STEP_LEFT, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.BIPED_STEP_RIGHT, 0.0F)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(40.0D)
                            .maxCooldown(160)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .custom(CombatCommon::canJump)
                                            .withinDistance(5.0D, 14.0D)
                                            .animationBehavior(Animations.BIPED_JUMP, 0.0F)
                                            .addExBehavior(CombatCommon::jump)
                            )
            );
}